/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      "colors": {
              "tertiary-container": "#2A2A2A",
              "surface-dim": "#080808",
              "secondary": "#666666",
              "on-primary": "#000000",
              "on-secondary-fixed-variant": "#444444",
              "on-tertiary-fixed": "#111111",
              "primary-container": "#FF4B00",
              "on-tertiary-fixed-variant": "#333333",
              "on-error": "#690000",
              "tertiary": "#F0F0F0",
              "secondary-fixed-dim": "#555555",
              "surface": "#111111",
              "surface-variant": "#1A1A1A",
              "on-tertiary-container": "#888888",
              "inverse-primary": "#CC3C00",
              "on-surface-variant": "#888888",
              "surface-container-high": "#1E1E1E",
              "on-background": "#FFFFFF",
              "tertiary-fixed-dim": "#888888",
              "on-surface": "#FFFFFF",
              "inverse-surface": "#FFFFFF",
              "surface-container-lowest": "#000000",
              "surface-tint": "#FF4B00",
              "on-secondary-container": "#777777",
              "surface-container-highest": "#222222",
              "on-primary-container": "#E64400",
              "on-secondary-fixed": "#090909",
              "primary": "#FF4B00",
              "surface-container": "#111111",
              "on-tertiary": "#E0E0E0",
              "primary-fixed-dim": "#CC3C00",
              "error-container": "#930000",
              "surface-container-low": "#0A0A0A",
              "on-primary-fixed": "#330E00",
              "on-secondary": "#111111",
              "background": "#000000",
              "outline": "#444444",
              "secondary-container": "#222222",
              "primary-fixed": "#FF6B1A",
              "on-error-container": "#FFDADA",
              "outline-variant": "#333333",
              "error": "#FF4444",
              "on-primary-fixed-variant": "#661C00",
              "tertiary-fixed": "#E0E0E0",
              "surface-bright": "#222222",
              "inverse-on-surface": "#000000",
              "secondary-fixed": "#DDDDDD"
      },
      "fontFamily": {
              "display-lg": ["Inter", "sans-serif"],
              "label-sm": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "display-md": ["Inter", "sans-serif"],
              "label-md": ["Inter", "sans-serif"],
              "headline-sm": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "inter": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
              "display-md": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
              "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}],
              "headline-sm": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
};
